[tool.poetry]
name = "graphai-lib"
version = "0.0.1"
description = ""
authors = ["Aurelio AI <hello@aurelio.ai>"]
readme = "README.md"
packages = [{include = "graphai"}]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
semantic-router = ">=0.1.0.dev4"
networkx = "^3.4.2"
matplotlib = "^3.10.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.0"
ruff = "^0.1.5"
pytest = "^8.2"
pytest-mock = "^3.12.0"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.5.0"
pytest-asyncio = "^0.24.0"
mypy = "^1.7.1"
black = {extras = ["jupyter"], version = ">=23.12.1,<24.5.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
